### ISSUE TITLE
"Error: expected array with fields" when trace a "public virtual AsyncUnaryCall<T>" method

### ISSUE THREAD

**Issue by EtherealAO** [vfsfitvnm/frida-il2cpp-bridge#22]
(AsyncUnaryCall<T> is from gRPC C#)
(All of them have two overloads like
```
seen
```

This error will be throwed when tracing (all of simpleTrace,fullTrace,fullWithValuesTrace) them.
```
Il2Cpp.Tracer.fullTrace(
    domain.assemblies["seen"].image.classes[
      "seen"
    ]
  );
Error: expected array with fields
    at NativeFunction.<anonymous> (<anonymous>)
    at Il2CppMethod.invokeRaw (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:104:1)
    at Il2CppMethod.<anonymous> (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:112:1)
    at Il2CppObject.domain.assemblies.seen.image.classes.seen.methods.seen.implementation (agent/index.ts:83:52)
    at InvocationContext.replaceCallback (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:77:1)
    at NativeFunction.<anonymous> (<anonymous>)
    at Il2CppMethod.invokeRaw (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:104:1)
    at Il2CppMethod.<anonymous> (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:112:1)
    at Il2CppObject.method.implementation (node_modules/frida-il2cpp-bridge/dist/il2cpp/tracer.js:80:1)
    at InvocationContext.replaceCallback (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:77:1)
```
This error will cause a in-game exception.

But if i use
```
  domain.assemblies["seen"].image.classes[
    "seen"
  ].methods.seen.implementation = function (
    request: Il2Cpp.Object,
    b: Il2Cpp.Object,
    c: any,
    d: any
  ): any {
    console.log("field: " + req.fields["field"].value);
    return this.methods.seen.invoke(request, b, c, d);
  };
```
instead, it works fine.
So is this a bug or incorrect tracer usage? I trace the whole class to intercept methods sequence, it works fine on other classes without overloads and generics.

**Comment by vfsfitvnm** [comment]
@EtherealAO 
Hi, if it's an android app and that method is invoked at app startup (without requiring play time), I can definitely investigate. What's its name?

**Comment by EtherealAO** [comment]
> @EtherealAO
> Hi, if it's an android app and that method is invoked at app startup (without requiring play time), I can definitely investigate. What's its name?

_seen_
AuthorizeV3Async is called when try to log in, a Japan IP may be required.
You can try `seen` instead, which invoked at app startup.

**Comment by vfsfitvnm** [comment]
@EtherealAO 
Uhm, the app is just a blank screen to me; I can only dump it. I looked at how those functions are "encoded" (e.g. `fridaSignature`) and they look good to me. 
Would you add some prints here and see what happens?
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/method.ts#L148
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/tracer.ts#L95

**Comment by vfsfitvnm** [comment]
Oh, I managed to make it load to the main screen. All I have to do is to press the back button instead of "OK" when it warns me I don't have the google spyware framework installed.
I'll investigate soon

**Comment by vfsfitvnm** [comment]
It should be fixed now!
