### ISSUE TITLE
Cannot read property 'address' of undefined in unityVersion

### ISSUE THREAD

**Issue by Drakota** [vfsfitvnm/frida-il2cpp-bridge#26]
Hi @vfsfitvnm,
First off, congrats for the 0.5.0 release, there's some really nice features.

After updating to 0.5.0 from 0.2.4 , I'm unable to attach a script, I get this error:
```
Attaching...
TypeError: Cannot read property 'address' of undefined
 at Function.get unityVersion (node_modules/frida-il2cpp-bridge/dist/il2cpp/base.js:26:1
 at Function.descriptor.get (node_modules/decorator-cache-getter/dist/index.js:9:1
 at createMissingApi (node_modules/frida-il2cpp-bridge/dist/il2cpp/api.js:806:1
 at Function.get sources (node_modules/frida-il2cpp-bridge/dist/il2cpp/api.js:405:1
 at Function.descriptor.get (node_modules/decorator-cache-getter/dist/index.js:9:1
 at Function.r (node_modules/frida-il2cpp-bridge/dist/il2cpp/api.js:409:1
 at Function.get _getCorlib (node_modules/frida-il2cpp-bridge/dist/il2cpp/api.js:212:1
 at Function.descriptor.get (node_modules/decorator-cache-getter/dist/index.js:9:1
 at Function.initialize (node_modules/frida-il2cpp-bridge/dist/il2cpp/base.js:42:1) 
```

The problem lies here:
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/ae774b5213845a4a884833f15bb53d3617660e1e/src/il2cpp/base.ts#L30-L43

`scanSync` doesn't find the pattern in the selected range and returns undefined.

I've modified it to look like the previous version like this and this works fine on 0.5.0
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/90a4bcda2da4d918543f6da3a235ea00413b3b4d/src/il2cpp/variables.ts#L52-L76

Wanted to make a PR, but not sure why the change in this version.

**Comment by vfsfitvnm** [comment]
Hi!
This is interesting! I had to change that because of #8.
The "breaking" change is probably here: 
https://github.com/vfsfitvnm/frida-il2cpp-bridge/commit/ca39f03acebd1868e3cb8ce6566f6dcc22062b6a#diff-ebfe8a849fb3f2cdad0b82bb46e38ae6f2e44f944f0082771bab68e7a306dfc4L17.

I replaced `unityLibrary.enumerateRanges("r--").concat(Process.getRangeByAddress(unityLibrary.base))` because I thought `Process.getRangeByAddress(unityLibrary.base)` was enough.

Could you tell me your OS and the application name?

**Comment by Drakota** [comment]
Hey,
Windows 10H2 (OS Build 19042.1165), the game I tried it on was _seen_ which uses Unity 2018.4.20f1.

**Comment by vfsfitvnm** [comment]
Oh, it's windows. It makes sense.
I'll fix this regression within the next update!

**Comment by vfsfitvnm** [comment]
Let me know if there are problems, I don't have Windows so it's problematic for me to test every single version!

**Comment by Drakota** [comment]
Yup, I can confirm that v0.5.1 fixed this for me.

Thank you!
