### ISSUE TITLE
Generic handling error in unity 2017.4.39f1 and mscorlib 2.0.0.0

### ISSUE THREAD

**Issue by wg138940-zz** [vfsfitvnm/frida-il2cpp-bridge#28]
I encountered the following error when trying the [generic handling example](https://github.com/vfsfitvnm/frida-il2cpp-bridge#generics-handling) in version 2017.4.39f1:
```
[il2cpp] Couldn't find property "System.RuntimeType", did you mean "System.ValueType"?
    at Object.raise (node_modules/frida-il2cpp-bridge/dist/utils/console.js:10:1) 
    at Object.get (node_modules/frida-il2cpp-bridge/dist/utils/utils.js:28:1)     
    at Il2CppClass.inflate (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/class.js:136:1)
    at doHook (index.ts:17:42)
    at executor (node_modules/frida-il2cpp-bridge/dist/il2cpp/base.js:75:1)
```

I found that my mscorlib assembly is missing the System.RuntimeType class, so I modified the implementation of Il2CppClass.inflate() and Il2CppMethod.inflate() as follows:
```typescript
// Il2CppClass.inflate()
inflate(...classes) {
        if (!this.isGeneric) {
            console_1.raise(`Cannot inflate ${this.type.name} because it's not generic.`);
        }
        const typeArray = Il2Cpp.Array.from(Il2Cpp.Image.corlib.classes["System.Type"], classes.map(klass => klass.type.object));
        //static System.Type MakeGenericType(System.Type gt, System.Type[] types);
        const inflatedType = Il2Cpp.Image.corlib.classes["System.Type"].methods.MakeGenericType.invoke(this.type.object, typeArray);
        return new Il2Cpp.Class(Il2Cpp.Api._classFromSystemType(inflatedType));
    }
```

```typescript
//Il2CppMethod.inflate()
inflate(...classes) {
        if (!this.isGeneric) {
            console_1.raise(`Cannot inflate ${this.name} because it's not generic.`);
        }
        const typeArray = Il2Cpp.Array.from(Il2Cpp.Image.corlib.classes["System.Type"], classes.map(klass => klass.type.object));
        const inflatedMethodObject = this.object.methods.MakeGenericMethod.invoke(typeArray);
        return new Il2Cpp.Method(Il2Cpp.Api._methodGetFromReflection(inflatedMethodObject));
    }
```

Then the Il2CppClass.inflate() error disappears, but the Il2CppMethod.inflate() still has the error:
```
[il2cpp] Couldn't resolve export "il2cpp_method_get_from_reflection".
    at Object.raise (node_modules/frida-il2cpp-bridge/dist/utils/console.js:10:1) 
    at Function.r (node_modules/frida-il2cpp-bridge/dist/il2cpp/api.js:1344:1)    
    at Function.get _methodGetFromReflection (node_modules/frida-il2cpp-bridge/dist/il2cpp/api.js:335:1)
    at Function.descriptor.get (node_modules/decorator-cache-getter/dist/index.js:9:1)
    at Il2CppMethod.inflate (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:100:1)
    at doHook (index.ts:36:42)
    at executor (node_modules/frida-il2cpp-bridge/dist/il2cpp/base.js:75:1)
```
It looks like this method is not available in the Il2Cpp API in version 2017.4.39f1. Is there any way to get this version of Il2Cpp to support generic methods?

Here is my source code: https://paste.ubuntu.com/p/bdwqsQxQsV/
Here is the Il2Cpp API definition of 2017.4.39f1: https://paste.ubuntu.com/p/s25HQJNtVb/

**Comment by vfsfitvnm** [comment]
I'm already aware of this and this is already fixed in local source code. This is what `il2cpp_method_get_from_reflection` does:
```c
struct Il2CppReflectionMethod
{
    Il2CppObject object;
    const MethodInfo * method;
    Il2CppString * name;
    struct Il2CppReflectionType * reftype;
};

const MethodInfo *
il2cpp_method_get_from_reflection (const Il2CppReflectionMethod * method)
{
    return method->method;
}
```

If you need it now, you can replace
```ts
Il2Cpp.Api._methodGetFromReflection(inflatedMethodObject)
```
with
```ts
inflatedMethodObject.handle.add(Process.pointerSize * 2).readPointer()
```
or
```ts
inflatedMethodObject.fields.mhandle.value as NativePointer
```
(not tested but they should work).

The fix will be out soon!
