### ISSUE TITLE
Error: access violation accessing 0x0

### ISSUE THREAD

**Issue by brianabdl** [vfsfitvnm/frida-il2cpp-bridge#40]
Game Unity Version : 5.6.4p4
frida-il2cpp-bridge Version : 0.5.8

Log Error :
```
[il2cpp] Dumping methods from Assembly-CSharp...
Error: access violation accessing 0x0
    at NativePointer.writePointer (frida/runtime/core.js:144:1)
    at write (node_modules/frida-il2cpp-bridge/dist/il2cpp/utils.js:95:1)
    at Il2CppPointer.set (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/pointer.js:43:1)
    at Il2CppPointer.write (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/pointer.js:49:1)
    at Il2CppPointer.set values [as values] (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/pointer.js:19:1)   
    at Function.from (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/array.js:18:1)
    at getTypeArray (node_modules/frida-il2cpp-bridge/dist/il2cpp/dumper.js:58:1)
    at Il2CppDumper.#generator (node_modules/frida-il2cpp-bridge/dist/il2cpp/dumper.js:64:1)
    at #generator.next (<anonymous>)
    at Il2CppDumper.build (node_modules/frida-il2cpp-bridge/dist/il2cpp/dumper.js:85:1)
```

it was be able to dump some methods then this error appear

**Comment by vfsfitvnm** [comment]
@Rewtio 
Hi, the game you are trying to dump contains customized [Il2Cpp structs](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/api.ts#L802).
In this scenario, you cannot trust any api that comes from the `CModule` in [this](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/api.ts#L1384) file.

You either have two options:
1 - Try to figure out what are the correct field offsets (trial and error approach, but a disassembler will be helpful).
These are the fixed (I guess) `Il2CppMethod` (aka `MethodInfo`) and `Il2CppParameter` (aka `ParameterInfo`) structs.
Please keep in mind that you might have to add or remove something else to make them 100% work.
```c
struct _Il2CppMethod
{
    void * pointer;
    void * invoker_method;
    const char * name;
    Il2CppClass * class;
    const Il2CppType * return_type;
    const Il2CppParameter * parameters;
    union
    {
        const struct Il2CppRGCTXData * rgctx_data;
        const struct Il2CppMethodDefinition * method_definition;
    };
    union
    {
        const Il2CppGenericMethod * generic_method;
        const Il2CppGenericContainer * generic_container;
    };
#if ${isBelow_2018_3_0}
    int32_t custom_attribute_index;
#endif
    char dummy[14]; // <--------- add this
    uint32_t token;
    uint16_t flags;
    uint16_t iflags;
    uint16_t slot;
    uint8_t parameter_count;
    uint8_t is_generic: 1;
    uint8_t is_inflated: 1;
#if ${isEqualOrAbove_2018_1_0}
    uint8_t wrapper_type: 1;
    uint8_t is_marshaled_from_native: 1;
#endif
};

struct _Il2CppParameter
{
    const char * name;
    int32_t position;
    uint32_t token;
#if ${isBelow_2018_3_0}
    int32_t custom_attribute_index; // <--------- remove this
#endif
    const Il2CppType * type;
};
```
2 - Avoid using the "corrupted" api: use the C# reflection api instead. (e.g. `Il2CppMethod` -> `System.Reflection.MethodInfo` -> then call `GetParameters()`). This requires a bit of work.

**Comment by vfsfitvnm** [comment]
Version `0.6.0` will be independent of Il2Cpp structs, so it will work.

**Comment by brianabdl** [comment]
Thank you
