### ISSUE TITLE
Expected array with fields when invoking function

### ISSUE THREAD

**Issue by RhythmLunatic** [vfsfitvnm/frida-il2cpp-bridge#50]
I want to invoke this function
```csharp

enum MoleMole.BundleType : System.Enum
{
	System.Int32 value__; // 0x10
	static MoleMole.BundleType DATA_FILE = 0;
	static MoleMole.BundleType RESOURCE_FILE = 1;
	static MoleMole.BundleType OBB_FILE = 2;
	static MoleMole.BundleType OBB_PART_FILE = 3;
}

System.String GetFileNameByAssetName(MoleMole.BundleType bundleType, System.String assetName); // 0x065c3098
```
But when I call it I get an error. Also, according to .parameters the parameters are `[Object object]`.
```ts
import "frida-il2cpp-bridge";

Il2Cpp.perform(() => {
	var img = Il2Cpp.Domain.assemblies['Assembly-CSharp'].image;
	var AssetBundleManagerV2 = img.classes['MoleMole.AssetBundleManagerV2']


	Il2Cpp.GC.choose(AssetBundleManagerV2).forEach((instance: Il2Cpp.Object) => {
		console.log(Object.keys(instance.methods))
		console.log(instance.methods.GetFileNameByAssetName.parameters);
		let value = Il2Cpp.String.from("Data/JsonData/TableToolsData");
		const output = instance.methods.GetFileNameByAssetName.invoke<Il2Cpp.String>(0,value)
		console.log(output);
	});
});
```
```
Error: expected array with fields
    at NativeFunction.<anonymous> (<anonymous>)
    at node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:171:1
    at Function.try (node_modules/frida-il2cpp-bridge/dist/il2cpp/base.js:116:1)
    at Il2CppMethod.invokeRaw (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:171:1)
    at Il2CppObject.GetFileNameByAssetName.implementation (index.ts:46:50)
    at InvocationContext.replaceCallback (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:120:1)
```

I'm not sure if it matters but it also passes itself when invoking the function?
```
[il2cpp] 0x065c3098 ┌─MoleMole.AssetBundleManagerV2.GetFileNameByAssetName(this = MoleMole.AssetBundleManagerV2, MoleMole.BundleType bundleType = RESOURCE_FILE, System.String assetName = "Miscs/AssetBundleAlwaysUseInstallConfig")
[il2cpp] 0x065c3098 └─MoleMole.AssetBundleManagerV2.GetFileNameByAssetName System.String = "miscs_assetbundlealwaysuseinstallconfig"
```

**Comment by vfsfitvnm** [comment]
Hi @RhythmLunatic!

The problem here is you are passing `bundleType` as `number`; however enum classes are value types. This is the Frida signature for that function:
```ts
const fun = new NativeFunction(ptr, "pointer", ["pointer", ["int32"], "pointer"]);
```
Solution: let `frida-il2cpp-bridge` convert the enum field to a `["int32"]` for you:

```ts
import "frida-il2cpp-bridge";

Il2Cpp.perform(() => {
	const img = Il2Cpp.Domain.assemblies['Assembly-CSharp'].image;
	const AssetBundleManagerV2 = img.classes['MoleMole.AssetBundleManagerV2'];
        const BundleType =  img.classes["MoleMole.BundleType"];
        const DATA_FILE = BundleType.fields.DATA_FILE.value;

	Il2Cpp.GC.choose(AssetBundleManagerV2).forEach((instance: Il2Cpp.Object) => {
		console.log(Object.keys(instance.methods))
		console.log(instance.methods.GetFileNameByAssetName.parameters);
		const value = Il2Cpp.String.from("Data/JsonData/TableToolsData");
		const output = instance.methods.GetFileNameByAssetName.invoke<Il2Cpp.String>(DATA_FILE, value)
		console.log(output);
	});
});
```

> Also, according to .parameters the parameters are [Object object].

This happens because `.parameters` is a special object. You can either iterate it:
```ts
for (const param of instance.methods.GetFileNameByAssetName.parameters) console.log(param);
```
or try to print it as an array:
```ts
console.log(Array.from(instance.methods.GetFileNameByAssetName.parameters));
```

**Comment by RhythmLunatic** [comment]
Oops, I forgot parameters was iterable.
Thank you for the help with enums, it works now.
